runtime: python3.11
memory_size: 512
timeout: 30
handler: lambda_function.lambda_handler
description: "Restore medical record to a previous version"
environment_variables:
  AWS_REGION: "us-east-1"
  DYNAMODB_MEDICAL_HISTORIES_TABLE: "medical_histories"
  DYNAMODB_VERSIONS_TABLE: "medical_record_versions"
